--- 
title: "Teste de uso do quarto feito totalmente no vim"
date: 29/05/2024
format: html
categories: [testes, R, quarto]
html:
    code-link = true
---

# Objetivos

1. Aumentar a prática com o vim e quarto, usando todas as funcionalidades aprendidas até o momento
2. Anotar os pontos de melhora 
3. Terminar os videos do canal post it para ter uma noção melhor do quarto
4. Anotar as dificuldades de uso

# Anotações

## vim
1. ele não tem coloração sem eu mecher nada, ao contrario do VS code, porém deve existir uma distro para ele sim.
2. Como deletar para tras/mover o cursor para trás.

## Quarto
1. Tem um recurso bom para anotação em slides e criar um quadro negro dentro dele, mas no formato reveljs, têm algo parecido no formato pptx ?
2. Testar fazer slides apenas em revealjs
3. Se eu formatar em varios formatos de output isso irá criar varios formatos de outputs direitinho, pq otimizando para o revieljs talvez fique errado em outros formatos. 


### link all the native funtions on the code
 
```
---
title "linkar funções"
format: 
  html:
    code-link = true
---
```

### esconder os blocos de codigo

$````{r}
#| include :false

show('hello world')


````

### Fazer anotações em slides e quadro negro


```
---
title "linkar funções"
format:
	revealjs:
		chalkboard: true 
---
```


### Mostrar codigo em slides no formato revealjs


```
---
title "linkar funções"
format:
	revealjs:
		chalkboard: true
execute: 
	echo: true 
---
```

### Fazer texto do codigo destacar, mostrando eles no slide

* A barra vertical sinboliza uma pausa na exibição dos slides.
````
#| code-line-numbers: "|9|10-11" 
````


##### Isso cria um problema de o codigo ficar grande demais pra se ver os gráficos/resultados dele, então para se esconder isso usa-se 

````
#| output-location: slide (ou qualquer outra opção)
````



